// Code generated by qtc from "hello.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/hello.qtpl:1
package templates

//line templates/hello.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/hello.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/hello.qtpl:1
func StreamHello(qw422016 *qt422016.Writer, name string) {
//line templates/hello.qtpl:1
	qw422016.N().S(`
	`)
//line templates/hello.qtpl:2
	qw422016.E().S(name)
//line templates/hello.qtpl:2
	qw422016.N().S(`!
`)
//line templates/hello.qtpl:3
}

//line templates/hello.qtpl:3
func WriteHello(qq422016 qtio422016.Writer, name string) {
//line templates/hello.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/hello.qtpl:3
	StreamHello(qw422016, name)
//line templates/hello.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line templates/hello.qtpl:3
}

//line templates/hello.qtpl:3
func Hello(name string) string {
//line templates/hello.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/hello.qtpl:3
	WriteHello(qb422016, name)
//line templates/hello.qtpl:3
	qs422016 := string(qb422016.B)
//line templates/hello.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/hello.qtpl:3
	return qs422016
//line templates/hello.qtpl:3
}
